### ISSUE TITLE
undefined symbol: luaL_prepbuffsize

### ISSUE THREAD

**Issue by zot24** [starius/lua-phpass#1]
I've been trying to run the following code:

```
local phpass = require 'phpass'
phpass.hashPassword(mysupersecretpassword)
```

But something goes wrong on `crypto.so`

```
2015/11/04 16:38:06 [error] 1013#0: *5 lua entry thread aborted: runtime error: error loading module 'crypto' from file '/opt/openresty/lualib/crypto.so':
    /opt/openresty/lualib/crypto.so: undefined symbol: luaL_prepbuffsize
```

Just wondering if anyone have had this problem before, I have install all dependencies using `luarocks`, I'm using version 5.2 of `lua` and I got `LuaXML` installed.

Am I missing something?

**Comment by starius** [comment]
OpenResty uses LuaJIT, which is compatible with Lua 5.1, not Lua 5.2. Symbol `luaL_prepbuffsize` was introduced in Lua 5.2, so Lua 5.1 doesn't have this symbol. You have to use Lua 5.1 based LuaRocks to install modules for OpenResty correctly.

**Comment by zot24** [comment]
Thanks @starius very helpful tip :+1:
